### ISSUE TITLE
Never ever change an API in the middle

### ISSUE THREAD

**Issue by dtaht** [dtaht/tc-adv#15]
@kdarbyshirebryant @rmounce 

I just pulled this to see this

       TCA_CAKE_OVERHEAD,
        TCA_CAKE_MPU, nonononono
        TCA_CAKE_RTT,

When it needed to be at the end (after wash), so as to not break userspace. Is this new MPU param, in this order, in any form, anywhere we can't fix it? (e.g. lede?).

Also the pull I just merged had no wash in it in the first place for tc, and it's inserted in the wrong place on cake, also. So what I want to do is pull wash for tc-adv (where is it?), then move MPU to after wash, in both the sch_cake and tc cases.

**Comment by dtaht** [comment]
OK, I just pushed a fix for cake, and customized my tc to be more correct. where's tc-adv wash?

**Comment by rmounce** [comment]
Makes sense. The MPU parameter hasn't hit LEDE, or anywhere other than a test branch of Kevin's as far as I'm aware.

Edit: I stand corrected, MPU was merged into LEDE yesterday with the parameters in in the 'wrong' order. Oops.

https://github.com/lede-project/source/commit/e38bafb65ae05e230d77208b35a71f5b8e21cd98
https://github.com/lede-project/source/commit/a40f3f90d61146d369dc13083e06fef69c08cdb3

Wash for tc-adv looks like it is in Kevin's tc-adv branch, as well as in the tc patch for cake in LEDE.
https://github.com/kdarbyshirebryant/tc-adv/commit/fb56c20b2bda793a0b47a7d5c56043a7d14b38ea

**Comment by dtaht** [comment]
AGGH

**Comment by dtaht** [comment]
everybody repeat after me: never break userspace. never break userspace. never break userspace.

**Comment by dtaht** [comment]
Given a choice between breaking everybody downstream of the main sch_cake repo (of which there are a few), and lede for a few more days, I'd rather break lede. So that's what I'm going to do.

**Comment by rmounce** [comment]
Kevin has kindly synced both the cake package and the tc patch in both affected branches of LEDE a few weeks ago. In addition to "unifying" the API, these now point upstream rather than to Kevin's branch. FWIW the "broken" API was only in LEDE for a few days and was internally consistent between cake and tc so any builds made in this window are still usable.

I'd like to apologise for any grief my little oversight has caused. As the situation now appears to be fully resolved, this issue can probably be closed.
